name: Construir APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Chequear c√≥digo
      uses: actions/checkout@v4

    - name: Instalar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'

    - name: Instalar dependencias
      run: |
        pip install flet
        dart pub global activate flet

    - name: Compilar APK
      run: flet build apk --verbose

    - name: Subir APK
      uses: actions/upload-artifact@v4
      with:
        name: app-ashram-ganesha
        path: build/app/outputs/flutter-apk/app-release.apk
